name: Actualizar Horarios de Tren

on:
  # Ejecuci칩n autom치ticatodos los lunes a las 8 AM UTC
  schedule:
    - cron: '0 8 * * 1'
  # 2. O permite que lo ejecutes manualmente con un click desde la web de GitHub
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Chequear el repositorio
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Instalar dependencias
      run: |
        pip install -r .\utils\requirements.txt

    - name: Correr script de procesamiento
      run: |
        python .\code\procesar_horarios.py

    - name: Guardar cambios (Commit & Push)
      run: |
        git config --global user.name 'yezdev7'
        git config --global user.email 'yezdev7@github.com'
        git add *.json
        # Solo hace commit si hubo cambios reales en los archivos
        git diff --quiet && git diff --staged --quiet || (git commit -m "Actualizaci칩n autom치tica de horarios" && git push)
